"""add completion_code and confirmed_by

Revision ID: 23b87172bed6
Revises:
Create Date: 2026-01-24 10:40:41.554081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23b87172bed6"
down_revision = "b181c921e012"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
