"""Fix Offer model duplicates

Revision ID: 55b74fb0edea
Revises: e43d44a90c0e
Create Date: 2026-01-24 12:00:16.676610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b74fb0edea'
down_revision: Union[str, None] = 'e43d44a90c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
