"""create offers table

Revision ID: b181c921e012
Revises: 55b74fb0edea
Create Date: 2026-01-24 12:47:22.167500
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

## revision identifiers, used by Alembic.
revision = "b181c921e012"
down_revision = "3e813ce14fb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
