"""fix primary key on offers

Revision ID: e43d44a90c0e
Revises: 23b87172bed6
Create Date: 2026-01-24 11:02:02.610692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e43d44a90c0e"
down_revision = "23b87172bed6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
